stages:
- name: script
  steps:
  - runScriptConfig:
      image: golang:latest
      shellScript: |-
        go get github.com/go-redis/redis
        go get github.com/go-sql-driver/mysql
        go get github.com/gorilla/mux
        go get github.com/jinzhu/gorm
        go install main
        ls bin
    env:
      GOPATH: /go/ITflow
timeout: 60
notification: {}
